name: Build and Push Docker Image
on:
  push:
    branches:
      - main
jobs:
  build-and-push-image:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: oeckikekk/munjigoorm-back:${{ github.sha }}

    - name: Move Repository
      uses: actions/checkout@master
      with:
        repository: munji-goorm/manifest
        token: ${{ secrets.ACTION_TOKEN }}
        path: manifest
    
    - name: Edit Manifest Image
      run: |
        cd manifest
        sed -i "39 c\        image: oeckikekk/munjigoorm-back:${{ github.sha }}" back-deploy.yaml
        git config --global user.email "no02031@naver.com"
        git config --global user.name "soyeonnn"
        git add .
        git commit -m "Edit back image"
        git push -f --set-upstream origin main
